
services:
  punto-h-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: punto-h-front
    ports:
      - "8080:80"
    restart: always
    networks:
      - my-microservices-net

networks:
  my-microservices-net:
    external: true
